# -*- coding: utf-8 -*-
"""Prompt_Engineering_LangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_maqR-DVDLPtBmQRosp4c7RZ7IsTdPcN
"""

!pip install langchain langchain-core langchain-community

"""Task 1: PromptTemplate"""

from langchain_core.prompts import PromptTemplate

template = PromptTemplate(
    input_variables=["topic"],
    template="Explain {topic}"
)

print(template.format(topic="AI"))

"""Task 2: Multi Input Prompt"""

template_2 = PromptTemplate(
    input_variables=["topic", "audience", "tone"],
    template="Explain {topic} for {audience} in a {tone} tone"
)

print(template_2.format(topic="AI", audience="beginners", tone="friendly"))
print(template_2.format(topic="Python", audience="kids", tone="fun"))
print(template_2.format(topic="Deep Learning", audience="engineers", tone="technical"))

"""Task 3: Prompt Variations"""

teaching_template = PromptTemplate(
    input_variables=["topic"],
    template="Explain {topic} clearly step by step"
)

interview_template = PromptTemplate(
    input_variables=["topic"],
    template="Ask 3 questions about {topic}"
)

story_template = PromptTemplate(
    input_variables=["topic"],
    template="Explain {topic} as a story"
)

topic = "Machine Learning"

print(teaching_template.format(topic=topic))
print(interview_template.format(topic=topic))
print(story_template.format(topic=topic))

"""Task 4: ChatPromptTemplate"""

from langchain_core.prompts import ChatPromptTemplate

chat_template = ChatPromptTemplate.from_messages([
    ("system", "You are a {role}"),
    ("user", "Explain {topic}")
])

messages = chat_template.format_messages(
    role="teacher",
    topic="Neural Networks"
)

print(messages)

"""Task 5: Input Validation"""

def validate_inputs(audience, tone):
    valid_audience = ["beginner", "intermediate", "expert"]
    valid_tone = ["formal", "casual", "fun"]

    if audience not in valid_audience:
        print("Invalid audience! Setting default = beginner")
        audience = "beginner"

    if tone not in valid_tone:
        print("Invalid tone! Setting default = formal")
        tone = "formal"

    return audience, tone

"""Task 6: Prompt Generator App"""

def generate_prompt(topic, audience, tone, style):

    audience, tone = validate_inputs(audience, tone)

    templates = {
        "teaching": "Explain {topic} for {audience} in a {tone} teaching style",
        "interview": "Ask interview questions on {topic} for {audience} in a {tone} tone",
        "storytelling": "Explain {topic} for {audience} in a {tone} storytelling style"
    }

    prompt_template = PromptTemplate(
        input_variables=["topic", "audience", "tone"],
        template=templates[style]
    )

    return prompt_template.format(
        topic=topic,
        audience=audience,
        tone=tone
    )

print(generate_prompt("Neural Networks", "beginner", "fun", "storytelling"))

"""Task 7: Reusability Test"""

reusable_template = PromptTemplate(
    input_variables=["topic"],
    template="Explain {topic} in simple terms"
)

topics = ["AI", "Python", "Blockchain", "Cloud Computing", "Data Science"]

for t in topics:
    print(reusable_template.format(topic=t))

